groups:
  - name: example
    rules:
      - alert: Service_Down
        expr: up{job="spring-actuator", instance="localhost:8080"} == 0
        labels:
          severity: 'O serviço está indisponível'
        # annotations:
        #   description: Service {{ $labels.instance }} is unavailable.
        #   value: DOWN ({{ $value }})

      - alert: CPU_Rate_High
        expr:  system_cpu_usage{instance='localhost:8080', job='spring-actuator'} > 0.1 #para definir este número, basta iniciar teste com o locust, e monitorar a app pela UI do prometheus, e analisar o valor retornado quando a app cai. A partir deste valor, definimos o limite a ser usado 
        labels:
          severity: 'Risco de indisponibilidade: CPU'
        # annotations:
        #   summary: WARN ! CPU High


# groups:
# - name: alert.rules
#   rules:
#   - alert: InstanceDown
#     expr: up == 0
#     for: 1m
#     labels:
#       severity: "critical"
#     annotations:
#       summary: "Endpoint {{ $labels.instance }} down"
#       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
  
#   - alert: HostOutOfMemory
#     expr: node_memory_MemAvailable / node_memory_MemTotal * 100 < 25
#     for: 5s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Host out of memory (instance {{ $labels.instance }})"
#       description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


#   - alert: HostOutOfDiskSpace
#     expr: (node_filesystem_avail{mountpoint="/"}  * 100) / node_filesystem_size{mountpoint="/"} < 50
#     for: 1s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Host out of disk space (instance {{ $labels.instance }})"
#       description: "Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


#   - alert: HostHighCpuLoad
#     expr: (sum by (instance) (irate(node_cpu{job="prometheus",mode="idle"}[5m]))) > 0
#     for: 5s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Host high CPU load (instance {{ $labels.instance }})"
#       description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"