groups:
  - name: example
    rules:
      - alert: Service_Down
        expr: up{job="spring-actuator", instance="localhost:8080"} == 0
        labels:
          severity: 'Serviço indisponível'


      - alert: CPU_Rate_High
        expr:  system_cpu_usage{instance='localhost:8080', job='spring-actuator'} > 0.7
        labels:
          severity: 'Risco de indisponibilidade: CPU'

